/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aungep;

import java.awt.print.PrinterException;
import javax.swing.table.TableModel;

/**
 *
 * @author hp
 */
public class print extends javax.swing.JFrame {

    /**
     * Creates new form print
     */
    public print() {
        initComponents();
    }
    
    String lsubtotal;
    String lpay;
    String lbalance;
    
    public print(String subtotal,String pay,String balance,TableModel tableModel) throws PrinterException {
        initComponents();
        this.lsubtotal = subtotal;
        this.lpay = pay;
        this.lbalance = balance;
        
        txt_print.setText(txt_print.getText()+"*********************************\n");
        txt_print.setText(txt_print.getText()+"******** Aung EP Electronic ********\n");
        txt_print.setText(txt_print.getText()+"\n");
        txt_print.setText(txt_print.getText()+"Item" + "\t" + "Price" + "\t" + "Total" + "\n");
        
        for(int i=0; i<tableModel.getRowCount(); i++)
        {
            String item = (String) tableModel.getValueAt(i, 1);
            String price = (String) tableModel.getValueAt(i, 2);
            int total = (int) tableModel.getValueAt(i, 4);
            
            txt_print.setText(txt_print.getText() + item + "\t" + price + "\t" + total + "\n");
        }
        txt_print.setText(txt_print.getText()+"\n");
        txt_print.setText(txt_print.getText()+"\n");
        
        txt_print.setText(txt_print.getText()+"Total      : " + subtotal + "     \n");
        txt_print.setText(txt_print.getText()+"Pay        : " + pay + "     \n" );
        txt_print.setText(txt_print.getText()+"Balance  : " + balance + "     \n");
        
        
        txt_print.setText(txt_print.getText()+"\n\n");
        txt_print.setText(txt_print.getText()+"**********************************\n");
        txt_print.setText(txt_print.getText()+"************ Thank You ************\n");
        
        txt_print.print();

    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_print = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_print.setColumns(20);
        txt_print.setFont(new java.awt.Font("Zawgyi-One", 0, 13)); // NOI18N
        txt_print.setRows(5);
        jScrollPane1.setViewportView(txt_print);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_print;
    // End of variables declaration//GEN-END:variables
}
